# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(default='', max_length=3000, unique=True)),
                ('Proyecto', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Proyecto.NombreDeProyecto')),
            ],
        ),
        migrations.CreateModel(
            name='DatosVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Partida', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('Descripcion', models.CharField(default='', max_length=3000, unique=True)),
                ('TotalHoras', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('IngenieroA', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('TecnicoA', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('TecnicoB', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('Ayudante', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('Concepto', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Ingenieria.Concepto')),
            ],
        ),
    ]
