# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingenieria', '0002_auto_20170215_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosventa',
            name='Partida',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
