# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingenieria', '0003_auto_20170215_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosventa',
            name='Ayudante',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='datosventa',
            name='IngenieroA',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='datosventa',
            name='TecnicoA',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='datosventa',
            name='TecnicoB',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='datosventa',
            name='TotalHoras',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=19),
        ),
    ]
